spring:
  application:
    name: eureka
  profiles: default

server:
  port: 8071

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false

  instance:
    hostname: eureka

logging:
  level:
    org.springframework.cloud.eureka: DEBUG